# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 579b797a6dd7b538b894cd2c044299e5c3993478558717425588940a1232063e3fa8ba42a216f232654621dcdbb8e5d1310b1b4698466ddadaee5de3a2a37483

test:
  secret_key_base: 0248875a6d3cb325f39f8df0d1e3bc6dc812c9c1cd3e58bf51e1099f5138161f59938559b25aa695bb3f0b6847d5fab8e7bc89013c8d24f885f1d81af3d928d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
